apiVersion: v1
kind: Pod
metadata:
  name: mariadb-pod
  labels:
    app: mariadb
spec:
  containers:
    - name: mariadb
      image: mariadb:10.6
      ports:
        - containerPort: 3306
      envFrom:
        - configMapRef:
            name: mariadb-config
      volumeMounts:
        - name: mariadb-storage
          mountPath: /var/lib/mysql
  volumes:
    - name: mariadb-storage
      persistentVolumeClaim:
        claimName: mariadb-pvc