apiVersion: v1
kind: Service
metadata:
  name: mariadb-svc
spec:
  type: NodePort
  selector:
    app: mariadb
  ports:
    - port: 3306
      targetPort: 3306
      nodePort: 30306 # Port accessible depuis l'extérieur du cluster si besoin