apiVersion: v1
kind: Pod
metadata:
  name: rabbitmq-pod
  labels:
    app: rabbitmq
spec:
  containers:
    - name: rabbitmq
      image: rabbitmq:3-management
      ports:
        - containerPort: 5672   # Port de communication (AMQP)
        - containerPort: 15672  # Port de l'interface d'administration web
      envFrom:
        - configMapRef:
            name: rabbitmq-config
      volumeMounts:
        - name: rabbitmq-storage
          mountPath: /var/lib/rabbitmq
  volumes:
    - name: rabbitmq-storage
      persistentVolumeClaim:
        claimName: rabbitmq-pvc