apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-gateway-conf
data:
  default.conf: |
    server {
        listen 80;

        # Tout ce qui est POST va vers l'Ingestion
        location /api/data {
            proxy_pass http://ingestion-svc:80; 
        }

        # Tout ce qui est GET va vers la Lecture
        location /api/history {
            proxy_pass http://lecture-svc:80; 
        }
    }