apiVersion: v1
kind: Pod
metadata:
  name: ingestion-pod
  labels:
    app: ingestion
spec:
  containers:
    - name: api-ingestion
      image: meteo/api-ingestion:v1
      imagePullPolicy: Never
      ports:
        - containerPort: 3000
      env:
        - name: AMQP_URL
          value: "amqp://admin:adminpassword@rabbitmq-svc:5672"