apiVersion: v1
kind: Pod
metadata:
  name: lecture-pod
  labels:
    app: lecture
spec:
  containers:
    - name: api-lecture
      image: meteo/api-lecture:v1
      imagePullPolicy: Never
      ports:
        - containerPort: 3001
      envFrom:
        - configMapRef:
            name: mariadb-config
      env:
        - name: DB_HOST
          value: "mariadb-svc"