apiVersion: v1
kind: Pod
metadata:
  name: processor-pod
  labels:
    app: processor
spec:
  containers:
    - name: api-processor
      image: meteo/api-processor:v1
      imagePullPolicy: Never
      env:
        - name: AMQP_URL
          value: "amqp://admin:adminpassword@rabbitmq-svc:5672"
      envFrom:
        - configMapRef:
            name: mariadb-config